### ISSUE TITLE
An option to save the generated wallpapers.

### ISSUE THREAD

**Issue by deepu2** [glesik/wpgen#1]
Sometimes I create some good wallpaper and when I accidentally change the wallpaper, it's lost. So an option to save the wallpaper or make the app save the wallpaper automatically to a folder will be good.

**Comment by glesik** [comment]
I've added "Export last wallpaper" feature in 1.3.3. Please give it a try, it's now live in F-droid.

**Comment by deepu2** [comment]
Works great! Thank you
